[Feature] Register torchvision transforms into mmcls
open-mmlab/mmpretrain pull request #1265
Opened 2022-12-14 05:12 UTC by Ezra-Yu

## Motivation

Register torchvision transforms into mmcls

## Modification

Please briefly describe what modification is made in this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-03-10 02:03 UTC, YuanLiuuuuuu commented on mmcls/datasets/transforms/formatting.py
>  class ToNumpy(BaseTransform):
Maybe PILToNumpy is better?

2023-03-10 02:03 UTC, YuanLiuuuuuu commented on mmcls/datasets/transforms/formatting.py
>  class ToPIL(BaseTransform):
NumpyToPIL?

2023-03-10 02:06 UTC, YuanLiuuuuuu commented on mmcls/datasets/transforms/formatting.py
> +    def __init__(self, to_rgb: bool = False):
```suggestion
    def __init__(self, to_rgb: bool = False) -> None:
```

2023-03-10 02:07 UTC, YuanLiuuuuuu commented on mmcls/datasets/transforms/formatting.py
> +    def __init__(self, to_rgb: bool = False):
Please also check other return typehint

2023-03-15 08:22 UTC, YuanLiuuuuuu commented on mmcls/datasets/transforms/formatting.py
> +    def __init__(self, to_rgb: bool = False, dtype=None) -> None:
should be to_bgr

2023-03-16 08:19 UTC, YuanLiuuuuuu commented on mmcls/datasets/transforms/formatting.py
> +    def transform(self, results: Dict) -> Dict:
```suggestion
    def transform(self, results: dict) -> dict:
```
Please also check other parts

2023-04-12 10:00 UTC, fangyixiao18 requested changes

2023-04-12 10:00 UTC, fangyixiao18 commented on docs/en/api/data_process.rst
> +**3. USe TorchVision Augs Except ToTensor&Normalize**
```suggestion
**3. Use TorchVision Augs Except ToTensor&Normalize**
```

2023-04-13 03:26 UTC, fangyixiao18 approved these changes

2023-04-13 10:05 UTC, merged