feat: add eva02 backbone
open-mmlab/mmpretrain pull request #1450
Opened 2023-03-31 11:05 UTC by zzc98

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Add the EVA02 backbone.
paper: https://arxiv.org/abs/2303.11331
code: https://github.com/baaivision/EVA/tree/master/EVA-02

## Modification

- Add new backbone network EVA02
- Complete the network implementation and configuration files
- Complete the weight conversion according to the official repository
- Align the accuracy on the ImageNet1k validation set

## Use cases

```python
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='EVA02',
        arch='base',
        img_size=448,
        sub_ln=True,
        out_type='avg_featmap'),
    neck=None,
    head=dict(
        type='LinearClsHead',
        num_classes=1000,
        in_channels=768,
        loss=dict(
            type='LabelSmoothLoss', label_smooth_val=0.1, mode='original'),
    ),
    init_cfg=[
        dict(type='TruncNormal', layer='Linear', std=.02),
        dict(type='Constant', layer='LayerNorm', val=1., bias=0.),
    ],
    train_cfg=dict(augments=[
        dict(type='Mixup', alpha=0.8),
        dict(type='CutMix', alpha=1.0)
    ])
)
```

More details can be found in `configs/eva02/README.md`.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-04-03 11:58 UTC, Ezra-Yu reviewed
please rm `_base_.models.eva` folder and put the models cfg into every file of config/eva02/eva02_xxxx.py.

2023-04-03 11:58 UTC, Ezra-Yu commented on mmpretrain/models/backbones/eva02.py
> +class EVA02(BaseModule):
why not Inherit ViT? note this [PR](https://github.com/open-mmlab/mmclassification/pull/1447/files)

2023-04-03 11:58 UTC, Ezra-Yu commented on mmpretrain/models/backbones/eva02.py
> +        if self.q_bias is not None:
this section of code would be exe every iter. Can it be put in __init__.

2023-04-03 11:58 UTC, Ezra-Yu commented on mmpretrain/models/backbones/eva02.py
> +class SwiGLU(BaseModule):
`SwiGLU` -> `SwiGLUFFN`

2023-04-03 11:58 UTC, Ezra-Yu commented on mmpretrain/models/backbones/eva02.py
> +class Block(BaseModule):
EVA02EndcoderLayer？

2023-04-03 11:58 UTC, Ezra-Yu commented on mmpretrain/models/backbones/eva02.py
> +class RotaryEmbedding(BaseModule):
this module could be mv into `mmpretain/models/utils/postion_encoding.py`. unit test is needed.

2023-05-06 05:59 UTC, Ezra-Yu approved these changes
LGTM.

2023-05-06 09:49 UTC, fangyixiao18 requested changes

2023-05-06 09:49 UTC, fangyixiao18 commented on configs/eva02/metafile.yml
> +  - Name: eva02-tiny-p14_pre_in21k
rename like `vit-tiny-p14_eva02-pre_in21k`, check all `Name` in metafile

2023-05-06 09:49 UTC, fangyixiao18 commented on mmpretrain/models/backbones/eva02.py
> +class EVA02(VisionTransformer):
```suggestion
class ViTEVA02(VisionTransformer):
```

2023-05-06 09:49 UTC, fangyixiao18 commented on mmpretrain/models/backbones/eva02.py
filename: `vit_eva02.py`

2023-05-06 10:19 UTC, fangyixiao18 requested changes
config names

2023-05-06 10:19 UTC, fangyixiao18 commented on configs/eva02/eva02_base_p14_8xb16_in1k.py
> +        type='EVA02',
```suggestion
        type='ViTEVA02',
```

2023-05-06 10:54 UTC, fangyixiao18 commented on docs/en/api/models.rst
> +   EVA02
```suggestion
   ViTEVA02
```

2023-05-06 11:17 UTC, fangyixiao18 approved these changes

2023-05-06 11:28 UTC, merged