[DOC] Add doc for usage of confusion matrix
open-mmlab/mmpretrain pull request #1513
Opened 2023-04-24 13:40 UTC by XiudingCai

## Motivation

Add docs for useful_tools\confusion_matrix.md.

## Modification

1. Added mmpretrain\docs\en\useful_tools\confusion_matrix.md
2. Added mmpretrain\docs\zh_CN\useful_tools\confusion_matrix.md
3. Modified index.rst

2023-04-25 02:05 UTC, Ezra-Yu commented on docs/zh_CN/useful_tools/confusion_matrix.md
> +>>> from mmcls.evaluation import ConfusionMatrix
The library name has now been changed to mmpretrain.

2023-04-25 02:58 UTC, fangyixiao18 requested changes

2023-04-25 02:58 UTC, fangyixiao18 commented on docs/en/useful_tools/confusion_matrix.md
> +```python
```suggestion
```shell
```

2023-04-25 02:58 UTC, fangyixiao18 commented on docs/zh_CN/useful_tools/confusion_matrix.md
> +```python
```suggestion
```shell
```

2023-04-27 06:56 UTC, Ezra-Yu approved these changes
LGTM.

2023-04-27 06:56 UTC, merged