[Feature] Add retrieval mAP
open-mmlab/mmpretrain pull request #1552
Opened 2023-05-08 07:51 UTC by Ezra-Yu

## Motivation

Add retrieval mAP and unit tests relate to https://github.com/open-mmlab/mmpretrain/pull/980

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-05-09 11:15 UTC, fangyixiao18 requested changes

2023-05-09 11:15 UTC, fangyixiao18 commented on mmpretrain/evaluation/metrics/retrieval.py
> +    Examples:
please check the format in readthedocs
![image](https://github.com/open-mmlab/mmpretrain/assets/36138628/1437967f-703e-4743-947d-ad4bfa71646e)

2023-05-26 02:36 UTC, mzr1996 approved these changes

2023-05-26 02:39 UTC, fangyixiao18 approved these changes

2023-05-26 02:40 UTC, merged