Alexwangxiang/t sne visualize doc
open-mmlab/mmpretrain pull request #1555
Opened 2023-05-10 06:30 UTC by alexwangxiang

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-05-17 06:30 UTC, fangyixiao18 requested changes

2023-05-17 06:30 UTC, fangyixiao18 commented on docs/en/useful_tools/t-sne_visualization.md
> +MMPretrain provides `tools/visualization/vis_tsne.py` tool to visualize ... by t-SNE. Please install `sklearn` to calculate TSNE by `pip install scikit-learn`.
```suggestion
MMPretrain provides `tools/visualization/vis_tsne.py` tool to visualize high-dimensional data vectors by t-SNE. Please install `sklearn` to calculate TSNE by `pip install scikit-learn`.
```

2023-05-17 06:30 UTC, fangyixiao18 commented on docs/en/useful_tools/t-sne_visualization.md
> +To be added.
could you please update this part?

2023-05-17 06:30 UTC, fangyixiao18 commented on docs/zh_CN/useful_tools/t-sne_visualization.md
> +待添加。
could you please also update this part?

2023-05-26 09:18 UTC, Ezra-Yu commented on docs/zh_CN/useful_tools/t-sne_visualization.md
> +以下是在ImageNet数据集上训练的 MAE-ViT-base 模型上运行 t-SNE 可视化的一个样例。输入数据来自 ImageNet 验证集。
It needs to be explained here that MAE and some self-supervised pre-training algorithms do not have test_dataloader information. When analyzing such self-supervised algorithms, you need to add test_dataloader information in the config, or you can use '--test-cfg' to specify a file

2023-05-26 09:18 UTC, Ezra-Yu commented on docs/zh_CN/useful_tools/t-sne_visualization.md
> +## 如何可视化 CNN 分类器的t-分布随机邻域嵌入（如 ResNet-18 和 ResNet-50）
## 如何可视化分类算法的 t-SNE  (如 ResNet)

2023-05-26 09:18 UTC, Ezra-Yu commented on docs/zh_CN/useful_tools/t-sne_visualization.md
> +## 如何可视化自监督视觉 transformer 的t-分布随机邻域嵌入
## 如何可视化自监督算法的 t-SNE (如 MAE)

2023-05-26 09:18 UTC, Ezra-Yu commented on docs/zh_CN/useful_tools/t-sne_visualization.md
> +- `--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]`: 覆盖被使用的配置中的一些设定，xxx=yyy 格式的关键字-值对会被合并到配置文件中。override some settings in the used config, the key-value pair in xxx=yyy format will be merged into config
这里很多行没有翻译

2023-06-01 02:03 UTC, fangyixiao18 approved these changes

2023-06-01 02:04 UTC, merged