Bump version to v1.0.0rc8
open-mmlab/mmpretrain pull request #1583
Opened 2023-05-22 09:09 UTC by mzr1996

Please check the changelog.

2023-05-22 09:52 UTC, fangyixiao18 requested changes

2023-05-22 09:52 UTC, fangyixiao18 commented on README.md
> +- Support multiple multi-modal algorithms and inferencers. You can explore these features by the [gradio demo](https://github.com/open-mmlab/mmpretrain/tree/main/projects/gradio_demo)!
```suggestion
- Support multiple **multi-modal** algorithms and inferencers. You can explore these features by the [gradio demo](https://github.com/open-mmlab/mmpretrain/tree/main/projects/gradio_demo)!
```

2023-05-22 09:52 UTC, fangyixiao18 commented on README.md
> +- Register torchvision transforms into MMPretrain, you can now easily integrate torchvision's data augmentations in MMPretrain.
Add doc link?

2023-05-23 03:22 UTC, mzr1996 commented on README.md
> +- Register torchvision transforms into MMPretrain, you can now easily integrate torchvision's data augmentations in MMPretrain.
```suggestion
- Register torchvision transforms into MMPretrain, you can now easily integrate torchvision's data augmentations in MMPretrain. See [the doc](https://mmpretrain.readthedocs.io/en/latest/api/data_process.html#torchvision-transforms)
```

2023-05-23 03:22 UTC, merged