[Enhancement] Support deepspeed with flexible runner
open-mmlab/mmpretrain pull request #1673
Opened 2023-06-27 11:23 UTC by fanqiNO1

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Deepspeed is supported with flexible runner during the training of vit-large and vit-huge.

The performance of vit-large trained with deepspeed is: accuracy/top1: 85.5760 accuracy/top5: 97.4800

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

2023-06-27 11:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmpretrain?pullRequest=1673) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmpretrain?pullRequest=1673) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmpretrain?pullRequest=1673) it.</sub>

2023-06-28 09:49 UTC, fangyixiao18 requested changes

2023-06-28 09:49 UTC, fangyixiao18 commented on configs/mae/benchmarks/vit-huge-p14_8xb128-coslr-50e_in1k_deepspeed-zero3.py
please rename the file to `vit-huge-p14_8xb128-ds-zero3-coslr-50e_in1k.py`

2023-06-28 09:49 UTC, fangyixiao18 commented on configs/mae/benchmarks/vit-huge-p14_8xb128-coslr-50e_in1k_deepspeed-zero3.py
> +_base_ = [
better to inherit from file `vit-huge-p14_8xb128-coslr-50e_in1k` and remove unchanged keys

2023-06-28 09:49 UTC, fangyixiao18 commented on configs/mae/benchmarks/vit-large-p16_8xb128-coslr-50e_in1k_deepspeed-zero3.py
the same comments as vit-huge config

2023-06-28 11:34 UTC, fangyixiao18 requested changes

2023-06-28 11:34 UTC, fangyixiao18 commented on configs/mae/benchmarks/vit-huge-p14_8xb128-ds-zero3-coslr-50e_in1k.py
> +_base_ = [
```suggestion
_base_ = ['./vit-huge-p14_8xb128-coslr-50e_in1k.py']
```
only one file is enough, like https://github.com/open-mmlab/mmpretrain/pull/1675/files

2023-06-28 11:34 UTC, fangyixiao18 commented on configs/mae/benchmarks/vit-large-p16_8xb128-ds-zero3-coslr-50e_in1k.py
> +_base_ = [
the same as above

2023-06-28 15:22 UTC, OpenMMLab-Assistant-004 commented
Hi @fanqiNO1,

We'd like to express our appreciation for your valuable contributions to the mmpretrain. Your efforts have significantly aided in enhancing the project's quality.
It is our pleasure to invite you to join our community thorugh Discord_Special Interest Group (SIG) channel. This is a great place to share your experiences, discuss ideas, and connect with other like-minded people. To become a part of the SIG channel, send a message to the moderator, OpenMMLab, briefly introduce yourself and mention your open-source contributions in the #introductions channel. Our team will gladly facilitate your entry. We eagerly await your presence. Please follow this link to join us: ​https://discord.gg/UjgXkPWNqA.

If you're on WeChat, we'd also love for you to join our community there. Just add our assistant using the WeChat ID: openmmlabwx. When sending the friend request, remember to include the remark "mmsig + Github ID".

Thanks again for your awesome contribution, and we're excited to have you as part of our community!

2023-06-29 02:05 UTC, fangyixiao18 approved these changes

2023-06-29 02:16 UTC, merged