[Feature] Support LoRA
open-mmlab/mmpretrain pull request #1687
Opened 2023-07-04 08:40 UTC by fanqiNO1

## Motivation

Support LoRA.

## Modification

Support LoRA.

## Use cases

```python
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='LoRAModel',
        module=dict(
            type='VisionTransformer',
            arch='b',
            img_size=384,
            patch_size=16,
            drop_rate=0.1,
            init_cfg=dict(type='Pretrained', checkpoint='.')),
        alpha=16,
        rank=16,
        drop_rate=0.1,
        targets=[dict(type='qkv')]),
    neck=None,
    head=dict(
        type='VisionTransformerClsHead',
        num_classes=1000,
        in_channels=768,
        loss=dict(
            type='LabelSmoothLoss', label_smooth_val=0.1,
            mode='classy_vision'),
        init_cfg=[dict(type='TruncNormal', layer='Linear', std=2e-5)],
    ))
```

## Experiments

Use the vit-p16-224 pretrained on the imagenet-21k and fine tune on the imagenet1k with 384px.

The GPU memory consumption has been reduced  from 24GB to 17GB.

The number of trainable parameters has been reduced from 88M to 1.2M.

The current accuracy (the experiment is still running) is `accuracy/top1`: 83.6920, `accuracy/top5`: 96.9800.

The `accuracy/top1` from the original paper [An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale](https://arxiv.org/pdf/2010.11929.pdf) is 83.97.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-07-20 03:25 UTC, fangyixiao18 requested changes
1. provide an example lora config of ViT
2. add a lora weights merge script for users

2023-07-24 02:54 UTC, fangyixiao18 approved these changes

2023-07-24 03:11 UTC, mzr1996 requested changes

2023-07-24 03:11 UTC, mzr1996 commented on tools/model_converters/merge_lora_weight.py
> +    parser.add_argument('src', help='src detectron lora model path')
`detectron lora model`?

2023-07-24 03:11 UTC, mzr1996 commented on tests/test_models/test_peft/test_lora.py
> +
Remove it if it's useless

2023-07-24 03:30 UTC, mzr1996 approved these changes

2023-07-24 03:30 UTC, merged