[Enhancement] New Version of `config` Adapting Vision Transformer Algorithm
open-mmlab/mmpretrain pull request #1727
Opened 2023-07-26 22:39 UTC by zeyuanyin

ViT algorithm config files are added to adapt new version of `config`.

Based on https://github.com/open-mmlab/OpenMMLabCamp/discussions/339

## Motivation
MMEngine establishes a renovated configuration infrastructure enabling us to tailor the configuration files according to requirements.

## Modification

- Add 9 ViT config python files in mmpretrain/configs/vision_transformer/
- Add corresponding model, dataset, and  schedule config python files in mmpretrain/configs/_base_/
- All added config files adapt new version of `config`.

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-07-26 22:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmpretrain?pullRequest=1727) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmpretrain?pullRequest=1727) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmpretrain?pullRequest=1727) it.</sub>

2023-07-31 07:02 UTC, fangyixiao18 requested changes

2023-07-31 07:02 UTC, fangyixiao18 commented on mmpretrain/configs/vision_transformer/vit_base_p16_32xb128_mae_in1k.py
> +model.backbone.init_cfg = []
better to remove this line and write it in line 17 like `backbone=dict(drop_rate=0, drop_path_rate=0.1, init_cfg=None)`

2023-07-31 07:02 UTC, fangyixiao18 commented on mmpretrain/configs/vision_transformer/vit_base_p32_64xb64_in1k.py
> +        # loss=dict(type=CrossEntropyLoss, loss_weight=1.0),
why did you comment this line and wite it outside model in line 24？

2023-07-31 11:32 UTC, fangyixiao18 approved these changes

2023-08-02 02:06 UTC, merged

2023-08-02 07:02 UTC, OpenMMLab-Assistant-004 commented
Hi @zeyuanyin,

We'd like to express our appreciation for your valuable contributions to the mmpretrain. Your efforts have significantly aided in enhancing the project's quality.
It is our pleasure to invite you to join our community thorugh Discord_Special Interest Group (SIG) channel. This is a great place to share your experiences, discuss ideas, and connect with other like-minded people. To become a part of the SIG channel, send a message to the moderator, OpenMMLab, briefly introduce yourself and mention your open-source contributions in the #introductions channel. Our team will gladly facilitate your entry. We eagerly await your presence. Please follow this link to join us: ​https://discord.gg/UjgXkPWNqA.

If you're on WeChat, we'd also love for you to join our community there. Just add our assistant using the WeChat ID: openmmlabwx. When sending the friend request, remember to include the remark "mmsig + Github ID".

Thanks again for your awesome contribution, and we're excited to have you as part of our community!