Implement of Zero-Shot CLIP Classifier
open-mmlab/mmpretrain pull request #1737
Opened 2023-08-01 07:35 UTC by Coobiw

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

I implement a version of zero-shot CLIP. With evaluation on CIFAR100 and ImageNet1k, it has a small gap with the official one(OpenAI's).

## Modification

I've added the file in mmpretrain.models.multimodal.clip_zs and the config files in configs.clip_zs. Just run:

```
python tools/test.py configs/clip_zs/clip-vit-base-patch16_cifar100.py clip-vit-b-p16.pth
```

Get the checkpoint
```
pip install ftfy regex tqdm
pip install git+https://github.com/openai/CLIP.git

import clip
model,_ = clip.load('ViT-B/16')
ckpt = model.state_dict()
torch.save(ckpt,'clip-vit-b-p16.pth'
```

I've uploaded it on [clip-vit-b-p16.pth](https://github.com/Coobiw/modelhub/releases/download/clip/clip-vit-b-p16.pth) and [clip-vit-l-p14.pth](https://github.com/Coobiw/modelhub/releases/download/clip/clip-vit-l-p14.pth)

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

```
# ViT-B/16 for CIFAR100
python tools/test.py configs/clip_zs/clip-vit-base-patch16_cifar100.py clip-vit-b-p16.pth

# ViT-L/14 for CIFAR100
python tools/test.py configs/clip_zs/clip-vit-large-patch14_cifar100.py clip-vit-l-p14.pth

# ViT-B/16 for IN1k
python tools/test.py configs/clip_zs/clip-vit-base-patch16_in1k.py clip-vit-b-p16.pth

# ViT-L/14 for IN1k
python tools/test.py configs/clip_zs/clip-vit-large-patch14_in1k.py clip-vit-l-p14.pth
```
The result is shown in following format:
<img width="708" alt="image" src="https://github.com/open-mmlab/mmpretrain/assets/48615375/950f2afe-ef05-422a-bfff-7662c46eed4b">

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-08-17 02:13 UTC, fangyixiao18 requested changes

2023-08-17 02:13 UTC, fangyixiao18 commented on mmpretrain/models/multimodal/clip_zs/clip.py
> +    """The implementation of `ChineseCLIP <https://arxiv.org/abs/2211.01335>`_.
update docstrings to CLIP and CLIP's link

2023-08-31 03:23 UTC, fangyixiao18 requested changes

2023-08-31 03:23 UTC, fangyixiao18 commented on mmpretrain/models/multimodal/clip_zs/clip.py
> +class CLIP_zs(CLIP):
Rename to CLIPZeroShot, please also check other parts

2023-08-31 03:23 UTC, fangyixiao18 commented on configs/clip_zs/clip-vit-base-patch16_cifar100.py
move all these 4 configs to `configs/clip/` folder, and rename them to format like `clip_vit-base-p16_zeroshot-cls_cifar100.py`

2023-09-01 10:07 UTC, fangyixiao18 approved these changes

2023-09-04 02:30 UTC, merged

2024-09-01 08:06 UTC, npurson commented
Appreciating your implementation! It really helped me out a lot!

BTW, have you ever considered adding the usage instructions to the README within the clip configs? I struggled to find how to use this feature until I dug through the PRs.